In [1]:
import sim_working
import pickle
import numpy as np
import time
import pandas as pd

In [2]:
#'case_three',
#'case_two','case_three'
start = time.time()
for g in ['burden']:
    for p in [32]:
        t=sim_working.run_many('time_comp',['case_one'],0,1,7,'../distributions_rl4rl/','../../Downloads/pooling_results_testing/','None',time_cond=g,pop_size=p)
end = time.time()
print(end-start)




323.57405519485474


In [17]:
def get_most_recent_index(users,days):
    maxes = {}
    for i in range(len(users)):
        user_id = users[i]
        if user_id not in maxes:
            maxes[user_id] = 0
        if days[i]>days[maxes[user_id]]:
            maxes[user_id]=i
    return maxes

In [18]:
test = get_most_recent_index(t[1],t[3])

In [7]:
np.dot(np.ones(907),np.eye(907)).shape

(907,)

In [3]:
t

[array([ 0.1196595 ,  0.76528153,  3.11169114, -2.45913789, -0.68184645]),
 array([ 0.76528153,  0.20088827, -2.9722985 ,  2.32022378,  0.66969234]),
 array([  3.11169114,  -2.9722985 , -10.56633431,   9.06579448,
          2.57668469]),
 array([-2.45913789,  2.32022378,  9.06579448, -6.12486712, -2.01521529]),
 array([-0.68184645,  0.66969234,  2.57668469, -2.01521529,  0.40421177])]

In [ ]:
t[0].population[1].beta

In [ ]:
x = t[0].population[1].history

In [ ]:
y = t[0].population[1].history

In [ ]:
with open('../Downloads/pooling_results_testing/batch/case_one/population_size_32_update_days_7_short_static_sim_0.pkl','rb') as f:
    d = pickle.load(f)
with open('../Downloads/pooling_results_testing/personalized/case_one/population_size_32_update_days_7_short_static_sim_0.pkl','rb') as f:
    dd = pickle.load(f)

In [ ]:
x[pd.Timestamp('2015-08-30 10:00:00')]

In [ ]:
len(dd['gparams'].history)

In [ ]:
420*32