In [1]:
import sim_working
import pickle
import numpy as np
import pandas as pd

In [ ]:
t=sim_working.run_many('time_effects',['case_three'],0,1,7,'../distributions_rl4rl/','../../Downloads/pooling_results_testing/','None')





0.0433
0.0338
0.039259620010852814
0.030632739886641502
0.03559006005525589
0.027762718498706818
0.032258227467536926
0.025154223665595055
0.02923402562737465
0.02278805337846279
0.026489583775401115
0.02064232900738716
0.024000687524676323
0.018696656450629234
0.021743083372712135
0.016932813450694084
0.0196964330971241
0.015334175899624825


In [15]:
def cluster_by_group(population,mus):
    groups = {}
    
    for k,v in population.items():
        g = v.gid
        if g not in groups:
            groups[g]=[]
        groups[g].append(mus[k][-2])
    return groups

In [16]:
with open('../../look/temp_cov_8.pkl','rb') as f:
    t = pickle.load(f)

In [17]:
np.diagonal(t)

array([0.00991711, 0.00396265, 0.00488758, 0.00387342, 0.00526802])

In [18]:
np.array(f[2]).mean()

-0.03181125049099459

In [4]:
t[2].mus2

{0: array([-0.32112287,  0.23784313,  0.20541038, -0.16721567,  0.01293068]),
 1: array([-1.16721572,  0.23784313,  0.20541038, -0.16721567, -0.49426085]),
 2: array([-0.58500023,  0.23784313,  0.20541038, -0.16721567, -0.15455452]),
 3: array([-0.86509727,  0.23784313,  0.20541038, -0.16721567, -0.29414953]),
 4: array([-0.49064294,  0.23784313,  0.20541038, -0.16721567, -0.10624416]),
 5: array([-0.75862906,  0.23784313,  0.20541038, -0.16721567, -0.21943672]),
 6: array([-0.50556561,  0.23784313,  0.20541038, -0.16721567, -0.1138191 ]),
 7: array([-0.76859915,  0.23784313,  0.20541038, -0.16721567, -0.2133023 ]),
 8: array([-1.03527122,  0.23784313,  0.20541038, -0.16721567, -0.40839448]),
 9: array([-1.58081996,  0.23784313,  0.20541038, -0.16721567, -0.70649699]),
 10: array([-0.85818186,  0.23784313,  0.20541038, -0.16721567, -0.32470008]),
 11: array([-0.74049655,  0.23784313,  0.20541038, -0.16721567, -0.25673913]),
 12: array([-0.86272662,  0.23784313,  0.20541038, -0.16721567

In [3]:
with open('../../look/mtwo_27.pkl','rb') as f:
    mtwo = pickle.load(f)
with open('../../look/mone_27.pkl','rb') as f:
    mone = pickle.load(f)
with open('../../look/mthree_27.pkl','rb') as f:
    mthree = pickle.load(f)

In [5]:
eqs.count(False)

29

In [4]:
eqs = [np.all(mthree[i]==mtwo[i]) for i in range(mone.shape[0])]
    

In [6]:
mone[2538]

array([ 1.06418582,  0.        ,  0.        ,  0.        ,  0.        ,
        0.51492969,  0.        ,  0.        ,  0.        ,  0.01492969,
       -0.48507031,  0.        ,  0.        ,  0.        ,  0.01492969])

In [11]:
mtwo[3]

array([1. , 0. , 0. , 0. , 1. , 0.5, 0. , 0. , 0. , 0.5, 0.5, 0. , 0. ,
       0. , 0.5])

In [11]:
with open('../Downloads/pooling_results_testing/batch/case_one/population_size_32_update_days_7_short_static_sim_0.pkl','rb') as f:
    d = pickle.load(f)
with open('../Downloads/pooling_results_testing/personalized/case_one/population_size_32_update_days_7_short_static_sim_0.pkl','rb') as f:
    dd = pickle.load(f)

In [13]:
x[pd.Timestamp('2015-08-30 10:00:00')]

{'steps': 2.1824307449805813,
 'add': 0.0,
 'action': 0,
 'location': 0,
 'location_1': 0,
 'ltps': 2.3144147789124854,
 'location_2': 0,
 'location_3': 0,
 'study_day': 34,
 'decision_time': 1,
 'time': Timestamp('2015-08-30 10:00:00'),
 'avail': True,
 'prob': 0.5703922948921332,
 'dow': 1,
 'tod': 0,
 'weather': 1,
 'pretreatment': 0,
 'optimal_reward': 0.035282963245947874,
 'optimal_action': 1,
 'mu2': [0, 0, 0, 0, 0],
 'gid': 1}

In [23]:
len(dd['gparams'].history)

TypeError: object of type 'NoneType' has no len()

In [3]:
420*32

13440

In [4]:
import os

In [16]:
with open('../../look/temp_cov_4.pkl','rb') as f:
    t = pickle.load(f)

In [17]:
np.diagonal(t)

array([0.04631295, 0.01643922, 0.02059733, 0.01596524, 0.01934526])